package homepageheader_hotels;

public class HotelsWebElement {

    public static final String hotelsLinkLocator = "//a[@href='/Hotels']";
    public static final String whereToSearchBox = "//div[@data-test-attribute='typeahead-QuickLink_HOTELS_geopicker']//form//input[@aria-label='Search']";
    public static final String checkInBox = "//div[@data-test-target='picker-CHECKIN']";
    public static final String nextButton ="//button[@data-testid='nav_next']";
    public static final String checkOutBox = "//div[@data-test-target='picker-CHECKOUT']";
    public static final String checkInDate = "//div[@aria-label='Thu Jun 10 2021']";
    public static final String checkFromDate = "//div[@aria-label='Mon Jul 05 2021']";
    public static final String addRoomsButton = "//button[@data-test-target='ticker-plus-rooms']";
    public static final String addAdultsButton = "//button[@data-test-target='ticker-plus-adults']";
    public static final String addChildrenButton = "//button[@data-test-target='ticker-plus-children']";
    public static final String updateButton = "//button[normalize-space()='Update']";
    public static final String hotelsLocator = "//a[normalize-space()='Hotels']";
    public static final String hotelsMatchResults= "//div[@class='search-results-title']";
    public static final String searchBoxInputBox = "//input[@id='mainSearch']";
    public static final String searchButton = "SEARCH_BUTTON";
    public static final String queryResultText = "//span[@class='title-query']";
    public static final String clearField = "CLEAR_WHAT";
    public static final String currencyDropdownButton = "//button[@aria-label='Currency: A$ AUD']";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";
//    public static final String = "";


}
